### ISSUE TITLE
Cidades adicionais

### ISSUE THREAD

**Issue by jonathancbarros** [kelvins/Municipios-Brasileiros#1]
Eu posso fazer um pull-request com 170 cidades adicionais, algumas repetidas mas com pontuações diferentes (Ex: `` ao invés de ' em cidades como Olho D`água das Flores) e outras que você não possui nessa listagem, o único problema é que não registrei o código do IBGE, apenas os dados de Latitude e Longitude. Se achar interessante, é só falar.

**Comment by kelvins** [comment]
Oi Jonathan, acho que seria ótimo, o problema é que o código IBGE é utilizado como chave primária (PK) nessa tabela então ele deveria ser não nulo e ser único. Se você conseguisse registrar o código IBGE destas cidades faltantes seria perfeito. Abraço

**Comment by jonathancbarros** [comment]
Pois é, até o momento eu não consegui obter o código IBGE tendo o nome da cidade, apenas o contrário. Você sabe alguma ferramenta para fazer tal coisa?

**Comment by kelvins** [comment]
Você consegue obter o código IBGE, utilizando o nome do município, pelo próprio site do IBGE no seguinte link: http://www.ibge.gov.br/home/geociencias/areaterritorial/area.shtm

Também encontrei esta outra ferramenta que faz isso: http://www.roseno.info/cidadesconsulta.aspx

Porém o processo de busca é manual.

**Comment by kelvins** [comment]
Sobre a questão de inserir cidades repetidas com pontuação diferente não sei se seria uma boa ideia, pois como eu falei antes o código IBGE é utilizado como chave primária e é único para cada cidade. Por acaso você teria algum motivo específico para alterar a pontuação no nome da cidade? O exemplo que você deu de alterar para `` ao invés de ' em cidades como Olho d'Água das Flores acredito que não é relevante, pois (pelo que eu pesquisei no Google) o nome da cidade é mesmo "Olho d'Água das Flores". Em todo caso, se você encontrar alguma cidade com o nome/pontuação errada sinta-se à vontade para alterar e enviar um pull request. :)

**Comment by jonathancbarros** [comment]
Pois é, pelo jeito eu teria que coletar os códigos do IBGE manualmente, então vai levar um certo tempo. Concordo com você sobre as cidades duplicadas. Portanto, vou fazer isso aos poucos e logo logo te envio um pull-request. Como você recomenda? Faço um fork ou apenas clone e te envio um push?

**Comment by kelvins** [comment]
Legal, perfeito. Acho que pode ser um fork mesmo.
