### ISSUE TITLE
Fonte das informações

### ISSUE THREAD

**Issue by danieltdt** [kelvins/Municipios-Brasileiros#11]
De onde vem essas informações? Acho importante dizer em algum lugar de onde vem e qual o ano referência desses dados.

**Comment by kelvins** [comment]
Concordo. Também acho que seria importante informar de onde foi criada a base. O problema é que ela foi criada em 2014 durante um trabalho da faculdade e sinceramente não sei se tenho mais essa informação. Em todo caso, vou procurar e caso consiga encontrar irei incluir no README. Em relação ao ano de referência dos dados, não sei se seria relevante. A base foi criada em 2014 mas desde então vem sendo atualizada sempre que possível/necessário aqui no Github, geralmente de acordo com os dados atualizados do IBGE.

**Comment by mariovalney** [comment]
Na dúvida, há a base do IBGE:
https://downloads.ibge.gov.br/downloads_geociencias.htm
