### ISSUE TITLE
População

### ISSUE THREAD

**Issue by lazaronixon** [kelvins/Municipios-Brasileiros#12]
Primeiramente parabéns, ficou perfeito. Só ficou faltando a população.

**Comment by starknx** [comment]
https://pt.wikipedia.org/wiki/Lista_de_munic%C3%ADpios_do_Brasil_por_popula%C3%A7%C3%A3o

**Comment by starknx** [comment]
http://servicodados.ibge.gov.br/Download/Download.ashx?u=ftp.ibge.gov.br/Estimativas_de_Populacao/Estimativas_2017/estimativa_dou_2017.xls

**Comment by kelvins** [comment]
@starknx obrigado. Achei interessante a ideia de inserir a população. O único problema que vejo é que população é um dado variável pois ela muda a cada período de tempo. Neste caso, seria necessário um esforço maior para manter os dados sempre atualizados e não sei até que ponto isso valeria a pena.

Em todo caso, vou manter a issue aberta caso alguém tenha alguma opinião/sugestão sobre isso. Podemos discutir sobre o assunto.

Att.

**Comment by starknx** [comment]
O censo é feito a cada 10 anos somente. Porem parece que eles fazem estimativa a cada ano. Vou ver se encontro a do censo.

**Comment by helysousa** [comment]
As estimativas de população no IBGE encontram-se [aqui](https://www.ibge.gov.br/estatisticas-novoportal/sociais/populacao/9103-estimativas-de-populacao.html?=&t=downloads)

**Comment by kelvins** [comment]
Boa @helysousa. Então, aparentemente (olhei apenas um arquivo) as estimativas são feitas anualmente e não são feitas para todos os municípios do Brasil. Neste caso, acredito que faz mais sentido mesmo manter arquivos separados para armazenar os dados populacionais. Enfim, ultimamente estou meio sem tempo, mas se alguém tiver tempo e interesse em fazer isso, sinta-se à vontade. Vou manter a issue aberta para que outras pessoas possam se manifestar ou até que isso seja implementado. Valeu

**Comment by Gustavo-D** [comment]
Fiz um pull request sobre esta issue (modifiquei somente o .csv). Na minha opinião não existe necessidade de manter um arquivo separado com as populações - sim, é um dado que muda mas mesmo assim dificilmente muda significativamente. E se o critério para manter em arquivo separado for que o dado muda os próprios nomes dos municípios também podem mudar...além disso a usabilidade dos dados em arquivos separados fica prejudicada.

**Comment by kelvins** [comment]
Legal @Gustavo-D, vou dar uma olhada com calma assim que possível. Esses dados você tirou do site do IBGE sugerido pelo @helysousa? Valeu

**Comment by helysousa** [comment]
@Gustavo-D , minha opinião sobre arquivos separados é que enquanto quando há mudança de nome ela ocorre em poucos registros (2 ou 3, quando muito), no caso da população ela pode ocorrer potencialmente em todos os registros. A simples substituição do arquivo, com dados do ibge, seria mais rápida que a troca dos dados de população município por município. Se não for desenvolvido um sistema para fazer o merge, há potencialmente um ponto crítico de falha na consistência dos doados.

Um abraço.

**Comment by helysousa** [comment]
Mais um ponto a ser considerado sobre a separação da população e municípios, há uma Issue aberta para a separação do estado e municípios, como tem uma PR incluindo a população a ser liberada, há um bloqueio do arquivo sem que a alteração esteja ligada a população, se os arquivos fossem separados essa situação não ocorreria. Não quero dizer com isso que esteja errado, apenas é uma decisão de projeto que, como todas, tem pontos positivos e negativos.

**Comment by kelvins** [comment]
Estava pensando melhor sobre isso e acredito que não faz sentido incluir a população nos dados pelos seguintes motivos:
- a população é muito variável (como dito ela é estimada a cada ano); 
- o custo de manter isso atualizado é grande (seriam mais de 5 mil registros para atualizar todo ano) e acredito que não teria tempo para fazer isso;
- outro ponto é que hoje em dia os principais dados desse repo são geográficos então talvez dados populacionais fujam um pouco do escopo.

Por esses motivos estou fechando essa issue. Caso alguém tenha algum outro ponto que faça sentido em relação a incluir os dados populacionais podemos discutir novamente e se for o caso reabrir a issue.
