### ISSUE TITLE
Sistema de Coordenada Utilizado

### ISSUE THREAD

**Issue by brenolehmann** [kelvins/Municipios-Brasileiros#15]
Olá.
Muito bom o trabalho, estas informações vão ajudar muita gente.
apenas fiquei com uma dúvida. Para utilizar estas coordenadas em um sistema geo-espacial é necessário saber qual é o sistema de coordenadas utilizado. Vocês sabem qual é o sistemas de coordenadas para a Latitude e Longitude apresentadas?

**Comment by kelvins** [comment]
Olá @brenolehmann, as coordenadas geográficas utilizam um sistema de paralelos e meridianos. Neste caso, a latitude é definida com base na linha do Equador, enquanto a longitude é definida com base no meridiano de Greenwich.

Exemplo:
https://pt.wikipedia.org/wiki/Coordenadas_geogr%C3%A1ficas#/media/File:Mapa_coordenadas_geogr%C3%A1ficas_editado.jpg

Valeu
