### ISSUE TITLE
Cidades com codigo_ibge errado

### ISSUE THREAD

**Issue by xsbr** [kelvins/Municipios-Brasileiros#25]
Comparando com a base do IBGE (https://servicodados.ibge.gov.br/api/docs/localidades) percebi que tem algumas cidades com seus códigos do ibge trocado, segue a lista:

- Santa Terezinha do Progresso/SC - 4215687 (incorreto 4215695)
- Santiago do Sul/SC - 4215695 (incorreto 4215687)
- Laje/BA - 2918803 (incorreto 2918902)
- Lajedão/BA - 2918902 (incorreto 2919009)
- Lajedinho/BA - 2919009 (incorreto 2919058)
- Lajedo do Tabocal/BA - 2919058 (incorreto 2918753)
- Lagoa Real/BA - 2918753 (incorreto 2918803)

**Comment by kelvins** [comment]
Valeu @xsbr, você poderia dar uma olhada no PR https://github.com/kelvins/Municipios-Brasileiros/pull/26 por favor?
