### ISSUE TITLE
Adicionar referência de como os dados de geolocalização são obtidos

### ISSUE THREAD

**Issue by josersi** [kelvins/Municipios-Brasileiros#28]
Grato pelo repositório, vai me ajudar muito nos meus projetos!
Seria interessante ter uma sessão no README explicando como você fez para obter os dados de geolocalização.

**Comment by kelvins** [comment]
Olá @josersi, obrigado por abrir a issue. Acredito que ela tenha relação com a issue https://github.com/kelvins/Municipios-Brasileiros/issues/11.
A base foi criada em 2014 com base nos dados do IBGE mas infelizmente não tenho mais a informação exata de como ela foi criada. :disappointed:  Em todo caso, ela vem sendo atualizada ao passar dos anos pela comunidade.
Estou fechando a issue mas fique a vontade para reabrir se achar necessário.
