### ISSUE TITLE
Duas cidades não encontradas em Rio Grande do Sul 

### ISSUE THREAD

**Issue by justapixel** [kelvins/Municipios-Brasileiros#33]
De acordo com os dados de áreas territoriais de 2020 pelo IBGE([Link](https://www.ibge.gov.br/geociencias/organizacao-do-territorio/estrutura-territorial/15761-areas-dos-municipios.html?=&t=downloads))
Rio Grande do Sul possui as cidades Lagoa Mirim e Lagoa dos Patos de códigos 4300001 e 4300002 respectivamente, não presentes no conjuntos de dados do repositório

**Comment by helysousa** [comment]
Apesar de constarem esses dois códigos na lista de municípios, considerando a lista de municípios disponibilizada em https://cidades.ibge.gov.br/, creio que de fato essas duas cidades não existam e há um equívoco na lista. Até a pesquisa pelos dois no Google Maps não retorna a informação como cidade e sim como porções de água (lagoas no sentido geográfico) no Estado do Rio Grande do Sul.

![image](https://user-images.githubusercontent.com/10290341/119021728-256b4a80-b976-11eb-914d-f6e98823ce3e.png)

A imagem exibe a lista de municípios do RS que iniciam pela letra L.

**Comment by justapixel** [comment]
Ah entendi, são apenas porções de água que complementam a área territorial nacional.

Valeu pela explicação, fechando a issue aqui
