### ISSUE TITLE
Capital das cidades no arquivo SQL

### ISSUE THREAD

**Issue by joaopbini** [kelvins/Municipios-Brasileiros#36]
No arquivo SQL de municípios todos os municípios estão descritos como capital.
![image](https://user-images.githubusercontent.com/7405014/125987859-eed35abc-d743-41e4-b16e-1d98e2b1d4d5.png)

**Comment by kelvins** [comment]
Bem observado @joaopbini, muito obrigado.

Abri um PR com a correção, se você pudesse dar uma olhada ajudaria bastante :)

PR https://github.com/kelvins/Municipios-Brasileiros/pull/37

**Comment by joaopbini** [comment]
Boa @kelvins ! Parece estar tudo certo. Obrigado pela força e velocidade!
