### ISSUE TITLE
A cidade de Garopaba está situada no meio do oceano de acordo com a localização

### ISSUE THREAD

**Issue by laisportugal** [kelvins/Municipios-Brasileiros#4]
No arquivo "Municipios_Brasileiros.sql" o município de Garopaba/SC está com as inscrições de latitude e longitude: "-28.0186, -48.6199" . Porém ao pesquisar no google maps, esse ponto remete a um ponto no meio do oceano.  [`Veja aqui o link do google maps`](https://www.google.com.br/maps/place/28%C2%B001'07.0%22S+48%C2%B037'11.6%22W/@-28.0186,-48.6220887,17z/data=!3m1!4b1!4m5!3m4!1s0x0:0x0!8m2!3d-28.0186!4d-48.6199) .

Agradeço desde já! Meus parabéns pela iniciativa!

**Comment by kelvins** [comment]
Muito obrigado @laisportugal. Realmente, o ponto está próximo do município de Garopaba mas está dentro mar, o ideal seria as seguintes latitude e longitude: -28.027489, -48.619169. Assim que possível vou corrigir isto. Valeu pela dica.

**Comment by kelvins** [comment]
Problema resolvido no commit: a51ecb90c17bd751c9a6670e460880d861915bc9

**Comment by laisportugal** [comment]
Eu que agradeço @kelvins !
