### ISSUE TITLE
Cidade de Jordão no Acre divergente

### ISSUE THREAD

**Issue by leonardovsramos** [kelvins/Municipios-Brasileiros#42]
A cidade de Jordão no acre está com as seguintes coordenadas (-9.43091, -71.8974). Porém, a posição real é (-9.190884, -71.950312), distando quase 28 km da posição constante na base.

**Comment by kelvins** [comment]
Obrigado por reportar @leonardovsramos. Corrigido no commit https://github.com/kelvins/Municipios-Brasileiros/commit/194cfcc3062dfc8a8f55bfdc9a630b3aee1f59f4.
