### ISSUE TITLE
Adicionar Bairros das Cidades

### ISSUE THREAD

**Issue by edsonrbispo** [kelvins/Municipios-Brasileiros#43]
Será que conseguiria disponibilizar também o SQL dos bairros das cidades.

Desde já agradeço por compartilhar os arquivos. #sucesso

**Comment by kelvins** [comment]
Olá @edsonrbispo, infelizmente não temos esses dados hoje e considerando que cada município possui diversos bairros, ficaria difícil de incluir e manter esses dados no repositório.

De toda forma, obrigado pelo comentário/sugestão.
