### ISSUE TITLE
Erro na linha 4907 falta por a virgula no final

### ISSUE THREAD

**Issue by robertoconceicao** [kelvins/Municipios-Brasileiros#5]
Olá Kelvin,

Primeiramente gostaria de te agradecer por disponibilizar essas informações esta sendo muito útil, muito bom mesmo, parabéns. Tentei rodar o script aqui e deu erro na linha 4907 pq falta a virgula no final, no mas eh isso, se souber de mais alguma issues ou nova cidade te aviso por aqui, valew.

**Comment by kelvins** [comment]
Olá Roberto, 
de nada, que bom que a informação foi útil.

Obrigado por avisar, realmente a vírgula estava faltando na [linha 4917](https://github.com/kelvins/Municipios-Brasileiros/blob/master/Municipios_Brasileiros.sql#L4917) do SQL (o seu erro ocorreu na linha 4907 provavelmente por causa do comando `CREATE TABLE` no início do SQL).

O problema foi corrigido no commit: 5865941eaa77be7db3bc7013659bf928546d12a6

Caso encontre mais algum problema ou novo município pode enviar um PR ou criar uma nova issue.

Att.
