### ISSUE TITLE
arquivo sql com colunas fora da ordem

### ISSUE THREAD

**Issue by evertonramos** [kelvins/Municipios-Brasileiros#8]
repare que os 4 últimos registros estão fora da ordem... eles estão com estado e código do estado, diferente de todos os outros... e assim quebra o sql.

![captura de tela 2017-08-25 as 12 01 45](https://user-images.githubusercontent.com/788504/29719633-4b42df88-898d-11e7-8724-755bd084854a.png)

**Comment by kelvins** [comment]
Olá @evertonramos. Realmente. Estes registros foram incluídos no último [pull request](https://github.com/kelvins/Municipios-Brasileiros/pull/7) e eu não havia notado. Vou corrigir isso. Obrigado por avisar.
