### ISSUE TITLE
mogi mirim código ibge: 3530805 duplicada no SQL

### ISSUE THREAD

**Issue by evertonramos** [kelvins/Municipios-Brasileiros#9]
mogi mirim aparece duas vezes na lista com o mesmo código IBGE... uma está com o nome errado, escrito com J, a mogi mirim com J parece ter coordenadas mais precisas... 

![captura de tela 2017-08-25 as 14 39 17](https://user-images.githubusercontent.com/788504/29725657-3a7ab7b4-89a3-11e7-97e0-73f68bdb2604.png)

**Comment by kelvins** [comment]
@evertonramos este problema também ocorreu devido ao último [pull request](https://github.com/kelvins/Municipios-Brasileiros/pull/7). Vou corrigir. Obrigado.
